name: voila
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipywidgets
  - ipykernel
  - pandas
  - pip
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - jupyterlab-fasta
  - matplotlib==3.7.2
  - scipy
  - vega_datasets
  - ipyvolume
  - plotly==5.16.1
  - numpy==1.25.2
  - folium
  - requests

  - pip:
    - voila==0.5.5
    - voila-topbar==0.1.1
